"""
企业微信消息模板 — 变量列表数据模型
"""

VARIABLES = [
    # ── 公司维度 ──
    {"var": "{days}", "label": "本月剩余天数", "category": "公司"},
    {"var": "{CompanyName}", "label": "公司名称", "category": "公司"},
    {"var": "{companyOrderNum}", "label": "公司今日第几单", "category": "公司"},
    {"var": "{companyOrderNumMonth}", "label": "公司本月第几单", "category": "公司"},
    {"var": "{dayTask}", "label": "公司今日任务", "category": "公司"},
    {"var": "{totalAmountDay}", "label": "公司今日累计业绩", "category": "公司"},
    {"var": "{monthTask}", "label": "公司本月任务", "category": "公司"},
    {"var": "{totalAmountMonth}", "label": "公司本月累计业绩", "category": "公司"},
    {"var": "{companyMonthTaskDiff}", "label": "公司本月业绩差额", "category": "公司"},
    {"var": "{companyMonthTaskRate}", "label": "公司本月完成率", "category": "公司"},
    {"var": "{companyAccountNumMonth}", "label": "公司本月代账第几单", "category": "公司"},
    # ── 个人维度 ──
    {"var": "{SalesmanName}", "label": "签单人姓名", "category": "个人"},
    {"var": "{orderNum}", "label": "签单人本月第几单", "category": "个人"},
    {"var": "{dayPersonTask}", "label": "个人今日任务", "category": "个人"},
    {"var": "{totalAmountDay1}", "label": "个人今日累计业绩", "category": "个人"},
    {"var": "{monthPersonTask}", "label": "个人本月任务", "category": "个人"},
    {"var": "{totalAmountMonth1}", "label": "个人本月累计业绩", "category": "个人"},
    {"var": "{personMonthTaskDiff}", "label": "个人本月业绩差额", "category": "个人"},
    {"var": "{personMonthTaskRate}", "label": "个人本月完成率", "category": "个人"},
    {"var": "{accountNumMonth}", "label": "个人本月代账第几单", "category": "个人"},
    # ── 团队维度 ──
    {"var": "{departmentName}", "label": "签单团队名称", "category": "团队"},
    {"var": "{teamOrderNum}", "label": "团队本月第几单", "category": "团队"},
    {"var": "{teamDayTask}", "label": "团队今日任务", "category": "团队"},
    {"var": "{teamAmountDay}", "label": "团队今日累计业绩", "category": "团队"},
    {"var": "{teamMonthTask}", "label": "团队本月任务", "category": "团队"},
    {"var": "{teamAmountMonth}", "label": "团队本月累计业绩", "category": "团队"},
    {"var": "{teamMonthTaskDiff}", "label": "团队本月业绩差额", "category": "团队"},
    {"var": "{teamMonthTaskRate}", "label": "团队本月完成率", "category": "团队"},
    # ── 客户维度 ──
    {"var": "{Customer}", "label": "客户名称", "category": "客户"},
    {"var": "{CustomerSource}", "label": "客户来源", "category": "客户"},
    {"var": "{semSource}", "label": "SEM来源", "category": "客户"},
    {"var": "{keyword}", "label": "关键词", "category": "客户"},
    {"var": "{ProductName}", "label": "签单产品", "category": "客户"},
    {"var": "{SigningType}", "label": "签单类型", "category": "客户"},
    {"var": "{TaxationFormDate}", "label": "收款时间", "category": "客户"},
    {"var": "{ContactAmount}", "label": "合同金额", "category": "客户"},
    {"var": "{Amount}", "label": "实际收款", "category": "客户"},
    {"var": "{PerformanceAmount}", "label": "签单业绩", "category": "客户"},
    {"var": "{Remark}", "label": "备注", "category": "客户"},
    {"var": "{CustomerServiceName}", "label": "所属顾问", "category": "客户"},
    {"var": "{Number}", "label": "400号码", "category": "客户"},
    {"var": "{totalDeduction}", "label": "400成本", "category": "客户"},
    {"var": "{totalCost2}", "label": "400返点", "category": "客户"},
    {"var": "{IsOldCustomer}", "label": "是否老客户(1是0否)", "category": "客户"},
]

SAMPLE_VALUES = {
    "{days}": "21",
    "{CompanyName}": "深圳慧用心科技有限公司",
    "{companyOrderNum}": "8",
    "{companyOrderNumMonth}": "156",
    "{dayTask}": "50,000",
    "{totalAmountDay}": "62,800",
    "{monthTask}": "1,500,000",
    "{totalAmountMonth}": "1,382,600",
    "{companyMonthTaskDiff}": "117,400",
    "{companyMonthTaskRate}": "92.17%",
    "{companyAccountNumMonth}": "48",
    "{SalesmanName}": "张伟",
    "{orderNum}": "12",
    "{dayPersonTask}": "8,000",
    "{totalAmountDay1}": "16,500",
    "{monthPersonTask}": "200,000",
    "{totalAmountMonth1}": "235,800",
    "{personMonthTaskDiff}": "已完成",
    "{personMonthTaskRate}": "117.9%",
    "{accountNumMonth}": "5",
    "{departmentName}": "销售一部",
    "{teamOrderNum}": "48",
    "{teamDayTask}": "25,000",
    "{teamAmountDay}": "42,300",
    "{teamMonthTask}": "800,000",
    "{teamAmountMonth}": "892,500",
    "{teamMonthTaskDiff}": "已完成",
    "{teamMonthTaskRate}": "111.56%",
    "{Customer}": "深圳宏达贸易有限公司",
    "{CustomerSource}": "百度推广",
    "{semSource}": "百度",
    "{keyword}": "代理记账",
    "{ProductName}": "小规模代理记账",
    "{SigningType}": "新签",
    "{TaxationFormDate}": "2026-06-14",
    "{ContactAmount}": "6,800.00",
    "{Amount}": "6,800.00",
    "{PerformanceAmount}": "5,440.00",
    "{Remark}": "客户意向明确，当天签单",
    "{CustomerServiceName}": "李芳",
    "{Number}": "400-888-6666",
    "{totalDeduction}": "320.00",
    "{totalCost2}": "480.00",
    "{IsOldCustomer}": "1",
}
